<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>Script_Kiddie</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PublishAot>true</PublishAot>
    <InvariantGlobalization>true</InvariantGlobalization>
	<EnableSourceGenerator>true</EnableSourceGenerator>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Constants\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="HtmlAgilityPack" Version="1.12.4" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="10.0.9" />
    <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="10.0.9" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Resources\Localization\AccountServiceStr.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>AccountServiceStr.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Resources\Localization\AccountServiceStr.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>AccountServiceStr.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

</Project>
