//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScriptKiddie.WinUI.Resources.Localization {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AccountServiceStr {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AccountServiceStr() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ScriptKiddie.WinUI.Resources.Localization.AccountServiceStr", typeof(AccountServiceStr).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Successfully get account name: {0} 的本地化字符串。
        /// </summary>
        internal static string AccountNameSuccess {
            get {
                return ResourceManager.GetString("AccountNameSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Auto-login successful 的本地化字符串。
        /// </summary>
        internal static string AutoLoginSuccess {
            get {
                return ResourceManager.GetString("AutoLoginSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Begin logging in 的本地化字符串。
        /// </summary>
        internal static string BeginLoggingIn {
            get {
                return ResourceManager.GetString("BeginLoggingIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Warning: Use cookie option is enabled, but httpClientHandler.CookieContainer do not have any cookie. 的本地化字符串。
        /// </summary>
        internal static string EmptyCookieWarning {
            get {
                return ResourceManager.GetString("EmptyCookieWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please enter password 的本地化字符串。
        /// </summary>
        internal static string EnterPasswordPlaceholder {
            get {
                return ResourceManager.GetString("EnterPasswordPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please enter student ID 的本地化字符串。
        /// </summary>
        internal static string EnterUsernamePlaceholder {
            get {
                return ResourceManager.GetString("EnterUsernamePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Login 的本地化字符串。
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error caused by unknown reasons. Login failed. 的本地化字符串。
        /// </summary>
        internal static string LoginFailedForUnknownReason {
            get {
                return ResourceManager.GetString("LoginFailedForUnknownReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Login Success. 的本地化字符串。
        /// </summary>
        internal static string LoginSuccess {
            get {
                return ResourceManager.GetString("LoginSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Choose an option 的本地化字符串。
        /// </summary>
        internal static string LoginTitle {
            get {
                return ResourceManager.GetString("LoginTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Logout failed. 的本地化字符串。
        /// </summary>
        internal static string LogoutFailed {
            get {
                return ResourceManager.GetString("LogoutFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Current page is redirected to outside page: {0} 的本地化字符串。
        /// </summary>
        internal static string PageRedirectedToOtherUrl {
            get {
                return ResourceManager.GetString("PageRedirectedToOtherUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please enter valid password 的本地化字符串。
        /// </summary>
        internal static string PasswordNotValidMessage {
            get {
                return ResourceManager.GetString("PasswordNotValidMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Send post request 的本地化字符串。
        /// </summary>
        internal static string SendPost {
            get {
                return ResourceManager.GetString("SendPost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Building login data 的本地化字符串。
        /// </summary>
        internal static string UIA_BuildLoginData {
            get {
                return ResourceManager.GetString("UIA_BuildLoginData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot extract execution or encrypt salt in page. Login failed. 的本地化字符串。
        /// </summary>
        internal static string UIA_CannotExtractExecutionOrEncryptSaltError {
            get {
                return ResourceManager.GetString("UIA_CannotExtractExecutionOrEncryptSaltError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Load cookie option is enabled but cookie content is empty. Login failed. 的本地化字符串。
        /// </summary>
        internal static string UIA_CookieContentEmptyError {
            get {
                return ResourceManager.GetString("UIA_CookieContentEmptyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Login your account with gdut unified identity authentication center 的本地化字符串。
        /// </summary>
        internal static string UIA_Description {
            get {
                return ResourceManager.GetString("UIA_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You have enabled remember me option. 的本地化字符串。
        /// </summary>
        internal static string UIA_EnableRememberMe {
            get {
                return ResourceManager.GetString("UIA_EnableRememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Extract Value Failed:  的本地化字符串。
        /// </summary>
        internal static string UIA_ExtractValueFailed {
            get {
                return ResourceManager.GetString("UIA_ExtractValueFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Warning: Load cookie option is enabled but could not login in. 的本地化字符串。
        /// </summary>
        internal static string UIA_LoadCookieLoginFailedWarning {
            get {
                return ResourceManager.GetString("UIA_LoadCookieLoginFailedWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Login with gdut unified identity authenticaton center 的本地化字符串。
        /// </summary>
        internal static string UIA_Name {
            get {
                return ResourceManager.GetString("UIA_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This account is not common account or username or password is incorrect 的本地化字符串。
        /// </summary>
        internal static string UIA_UsernameNotValidError {
            get {
                return ResourceManager.GetString("UIA_UsernameNotValidError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Username or password is incorrect 的本地化字符串。
        /// </summary>
        internal static string UIA_UsernameOrPasswordIncorrect {
            get {
                return ResourceManager.GetString("UIA_UsernameOrPasswordIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You have a valid session. No need to login. 的本地化字符串。
        /// </summary>
        internal static string UIA_ValidSession {
            get {
                return ResourceManager.GetString("UIA_ValidSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Username or password wrong. Login failed 的本地化字符串。
        /// </summary>
        internal static string UIA_WrongUsernameOrPasswordMessage {
            get {
                return ResourceManager.GetString("UIA_WrongUsernameOrPasswordMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please enter valid username 的本地化字符串。
        /// </summary>
        internal static string UsernameNotValidMessage {
            get {
                return ResourceManager.GetString("UsernameNotValidMessage", resourceCulture);
            }
        }
    }
}
